---
kind: pipeline
type: kubernetes
name: upgrade-image

platform:
  os: linux
  arch: aarch64

trigger:
  branches:
    - v2.11.x
  event:
    - push

steps:
- name: build
  image: golang:1.14.7
  commands:
  - apk update
  - apk add gcc jq zip conntrack
  - apk add libudev-dev
  - make upgrade-image.arm64
