---
kind: pipeline
type: kubernetes
name: upgrade-image

platform:
  os: linux
  arch: aarch64

trigger:
  branches:
    - v2.11.x
  event:
    - push

steps:
- name: build
  image: golang:1.14.7
  commands:
  - apt update
  - apt install -y -qq gcc jq zip conntrack
  - apt install -y -qq libudev-dev
  - SRC_REPO="$(pwd)"
  - DST_REPO="$GOPATH/src/github.com/openebs/maya"
  - if [ "$SRC_REPO" != "$DST_REPO" ]; then
  - echo "Copying from $SRC_REPO to $DST_REPO"
  - echo "But first, get the git revision from $SRC_REPO"
  - GIT_COMMIT="$(git rev-parse HEAD)"
  - echo $GIT_COMMIT >> $SRC_REPO/GITCOMMIT
  - mkdir -p $DST_REPO
  - rsync -az ${TRAVIS_BUILD_DIR}/ ${DST_REPO}/
  - export TRAVIS_BUILD_DIR=$DST_REPO
  - cd $DST_REPO
  - fi
  - echo "" > $GOPATH/src/github.com/openebs/maya/BUILDMETA
  - make upgrade
